// Code generated by entc, DO NOT EDIT.

package group

import (
	"fmt"

	"gofriday.dev/awesome/ent/confirmstatus"
)

const (
	// Label holds the string label denoting the group type in the database.
	Label = "group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConfirmStatus holds the string denoting the confirm_status field in the database.
	FieldConfirmStatus = "confirm_status"
	// FieldResultAt holds the string denoting the result_at field in the database.
	FieldResultAt = "result_at"

	// Table holds the table name of the group in the database.
	Table = "groups"
)

// Columns holds all SQL columns for group fields.
var Columns = []string{
	FieldID,
	FieldConfirmStatus,
	FieldResultAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

const DefaultConfirmStatus confirmstatus.Status = "unknown"

// ConfirmStatusValidator is a validator for the "confirm_status" field enum values. It is called by the builders before save.
func ConfirmStatusValidator(cs confirmstatus.Status) error {
	switch cs {
	case "unknown", "confirm", "decline":
		return nil
	default:
		return fmt.Errorf("group: invalid enum value for confirm_status field: %q", cs)
	}
}
