// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"gofriday.dev/awesome/ent/confirmstatus"
	"gofriday.dev/awesome/ent/group"
	"gofriday.dev/awesome/ent/predicate"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where adds a new predicate for the builder.
func (gu *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	gu.mutation.predicates = append(gu.mutation.predicates, ps...)
	return gu
}

// SetConfirmStatus sets the confirm_status field.
func (gu *GroupUpdate) SetConfirmStatus(c confirmstatus.Status) *GroupUpdate {
	gu.mutation.SetConfirmStatus(c)
	return gu
}

// SetNillableConfirmStatus sets the confirm_status field if the given value is not nil.
func (gu *GroupUpdate) SetNillableConfirmStatus(c *confirmstatus.Status) *GroupUpdate {
	if c != nil {
		gu.SetConfirmStatus(*c)
	}
	return gu
}

// ClearConfirmStatus clears the value of confirm_status.
func (gu *GroupUpdate) ClearConfirmStatus() *GroupUpdate {
	gu.mutation.ClearConfirmStatus()
	return gu
}

// SetResultAt sets the result_at field.
func (gu *GroupUpdate) SetResultAt(t time.Time) *GroupUpdate {
	gu.mutation.SetResultAt(t)
	return gu
}

// SetNillableResultAt sets the result_at field if the given value is not nil.
func (gu *GroupUpdate) SetNillableResultAt(t *time.Time) *GroupUpdate {
	if t != nil {
		gu.SetResultAt(*t)
	}
	return gu
}

// ClearResultAt clears the value of result_at.
func (gu *GroupUpdate) ClearResultAt() *GroupUpdate {
	gu.mutation.ClearResultAt()
	return gu
}

// Mutation returns the GroupMutation object of the builder.
func (gu *GroupUpdate) Mutation() *GroupMutation {
	return gu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GroupUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gu.hooks) == 0 {
		if err = gu.check(); err != nil {
			return 0, err
		}
		affected, err = gu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gu.check(); err != nil {
				return 0, err
			}
			gu.mutation = mutation
			affected, err = gu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gu.hooks) - 1; i >= 0; i-- {
			mut = gu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GroupUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GroupUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gu *GroupUpdate) check() error {
	if v, ok := gu.mutation.ConfirmStatus(); ok {
		if err := group.ConfirmStatusValidator(v); err != nil {
			return &ValidationError{Name: "confirm_status", err: fmt.Errorf("ent: validator failed for field \"confirm_status\": %w", err)}
		}
	}
	return nil
}

func (gu *GroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   group.Table,
			Columns: group.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: group.FieldID,
			},
		},
	}
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.ConfirmStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: group.FieldConfirmStatus,
		})
	}
	if gu.mutation.ConfirmStatusCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: group.FieldConfirmStatus,
		})
	}
	if value, ok := gu.mutation.ResultAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: group.FieldResultAt,
		})
	}
	if gu.mutation.ResultAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: group.FieldResultAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// SetConfirmStatus sets the confirm_status field.
func (guo *GroupUpdateOne) SetConfirmStatus(c confirmstatus.Status) *GroupUpdateOne {
	guo.mutation.SetConfirmStatus(c)
	return guo
}

// SetNillableConfirmStatus sets the confirm_status field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableConfirmStatus(c *confirmstatus.Status) *GroupUpdateOne {
	if c != nil {
		guo.SetConfirmStatus(*c)
	}
	return guo
}

// ClearConfirmStatus clears the value of confirm_status.
func (guo *GroupUpdateOne) ClearConfirmStatus() *GroupUpdateOne {
	guo.mutation.ClearConfirmStatus()
	return guo
}

// SetResultAt sets the result_at field.
func (guo *GroupUpdateOne) SetResultAt(t time.Time) *GroupUpdateOne {
	guo.mutation.SetResultAt(t)
	return guo
}

// SetNillableResultAt sets the result_at field if the given value is not nil.
func (guo *GroupUpdateOne) SetNillableResultAt(t *time.Time) *GroupUpdateOne {
	if t != nil {
		guo.SetResultAt(*t)
	}
	return guo
}

// ClearResultAt clears the value of result_at.
func (guo *GroupUpdateOne) ClearResultAt() *GroupUpdateOne {
	guo.mutation.ClearResultAt()
	return guo
}

// Mutation returns the GroupMutation object of the builder.
func (guo *GroupUpdateOne) Mutation() *GroupMutation {
	return guo.mutation
}

// Save executes the query and returns the updated entity.
func (guo *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	var (
		err  error
		node *Group
	)
	if len(guo.hooks) == 0 {
		if err = guo.check(); err != nil {
			return nil, err
		}
		node, err = guo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = guo.check(); err != nil {
				return nil, err
			}
			guo.mutation = mutation
			node, err = guo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(guo.hooks) - 1; i >= 0; i-- {
			mut = guo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, guo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (guo *GroupUpdateOne) check() error {
	if v, ok := guo.mutation.ConfirmStatus(); ok {
		if err := group.ConfirmStatusValidator(v); err != nil {
			return &ValidationError{Name: "confirm_status", err: fmt.Errorf("ent: validator failed for field \"confirm_status\": %w", err)}
		}
	}
	return nil
}

func (guo *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   group.Table,
			Columns: group.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: group.FieldID,
			},
		},
	}
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Group.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := guo.mutation.ConfirmStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: group.FieldConfirmStatus,
		})
	}
	if guo.mutation.ConfirmStatusCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: group.FieldConfirmStatus,
		})
	}
	if value, ok := guo.mutation.ResultAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: group.FieldResultAt,
		})
	}
	if guo.mutation.ResultAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: group.FieldResultAt,
		})
	}
	_node = &Group{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
